{"timestamp":"2025-10-24T09:59:49.887682Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-24T09:59:49.890016Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/coresentiment_V2.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-24T09:59:52.409530Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.411985Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.415726Z","level":"info","event":"Current task name:get_next_file","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.418551Z","level":"info","event":"Dag name:core-sentiment-V2","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.614301Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"ConnectionError","exc_value":"HTTPSConnectionPool(host='dumps.wikimedia.org', port=443): Max retries exceeded with url: /other/pageviews/2025/2025-10/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f0b056d5dc0>: Failed to resolve 'dumps.wikimedia.org' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/coresentiment_V2.py","lineno":23,"name":"_get_next_file"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":73,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":677,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='dumps.wikimedia.org', port=443): Max retries exceeded with url: /other/pageviews/2025/2025-10/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f0b056d5dc0>: Failed to resolve 'dumps.wikimedia.org' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPSConnection object at 0x7f0b056d5dc0>: Failed to resolve 'dumps.wikimedia.org' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/python/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-24T09:59:52.628360Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.652397Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.655088Z","level":"info","event":"Task:<Task(PythonOperator): get_next_file>","logger":"task.stdout"}
{"timestamp":"2025-10-24T09:59:52.656055Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='dumps.wikimedia.org', port=443): Max retries exceeded with url: /other/pageviews/2025/2025-10/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f0b056d5dc0>: Failed to resolve 'dumps.wikimedia.org' ([Errno -2] Name or service not known)\"))","logger":"task.stdout"}
