{"timestamp":"2025-10-21T04:59:29.858564Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-21T04:59:29.861522Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/coresentiment.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-21T04:59:30.194884Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.199130Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.199816Z","level":"info","event":"Current task name:load_to_postgres","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.200466Z","level":"info","event":"Dag name:core-sentiment","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.401541Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `postgres_default` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/coresentiment.py","lineno":60,"name":"_load_to_postgres"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":319,"name":"get_sqlalchemy_engine"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py","lineno":176,"name":"sqlalchemy_url"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py","lineno":243,"name":"connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/hook.py","lineno":61,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":228,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":218,"name":"_handle_connection_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-21T04:59:30.432536Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.438455Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.440411Z","level":"info","event":"Task:<Task(PythonOperator): load_to_postgres>","logger":"task.stdout"}
{"timestamp":"2025-10-21T04:59:30.440974Z","level":"info","event":"Failure caused by The conn_id `postgres_default` isn't defined","logger":"task.stdout"}
